apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento2
  name: magento2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: magento2
